server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:mem:dev
    username: dev
    password:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create # validate | update | create | create-drop
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

exception:
  message:
    role: User authorization denied
    username: User authorization denied

springdoc:
  api-docs:
    path: /v3/api-docs-order
  swagger-ui:
    path: /swagger-order