spring:
  server:
    port: 8080
  webflux:
    static-path-pattern: ""
  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 5000ms
  redis:
    host: localhost
    port: 6379

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    reactor.netty.http.client: DEBUG
    org.springframework.security: DEBUG

exception:
  message:
    role: User authorization denied
    username: User authorization denied