spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/product/**
        - id: inventory-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/inventory/**
        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/order/**
  server:
    port: 8080
